/**
 * Component templates — thin wrapper around auto-generated templates.
 *
 * The actual template content is generated by scripts/gen-cli-templates.mjs
 * which reads the real component source files. Run `pnpm --filter @js-ds-ui/cli prebuild`
 * to regenerate after changing component source.
 */
export { getComponentTemplate, getAvailableTemplates } from './generated';
